remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"

title                    : "GitHub Pages 따라하기"
name                     : "코딩을 연습해요"
description              : "블로그"
url                      : "https://DAMHEE-K.github.io"
baseurl                  : # 서브 경로가 있는 경우 기재
